[package]
name = "rzip_cli"
version.workspace = true
edition.workspace = true

[dependencies]
rzip_lib = { path = "../../lib" }
clap = { version = "4.5.8", features = ["derive", "cargo"] }

[dev-dependencies]
tempfile = { workspace = true }
